name: Linux

on:
  push:
    branches:
      - main
      - release
      - rc/**

jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3.0.0
      - name: Cache build output
        uses: actions/cache@v3
        env:
          cache-name: cache-make-files
        with:
          path: out
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Run build script
        run: |
          cd build/linux && printf "y" | ./build.sh continuous
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: filament-linux
          path: out/filament-release-linux.tgz
